/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellUsuariosRouteImport } from './routes/_shell.usuarios'
import { Route as ShellRelatoriosRouteImport } from './routes/_shell.relatorios'
import { Route as ShellLaboratoriosRouteImport } from './routes/_shell.laboratorios'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellConfiguracoesRouteImport } from './routes/_shell.configuracoes'
import { Route as ShellAlertasIndexRouteImport } from './routes/_shell.alertas.index'
import { Route as ShellBancadasNovaRouteImport } from './routes/_shell.bancadas.nova'
import { Route as ShellAlertasDestinosRouteImport } from './routes/_shell.alertas.destinos'
import { Route as ApiPublicHooksCheckAlertsRouteImport } from './routes/api/public/hooks/check-alerts'
import { Route as ApiPublicBenchTelemetryRouteImport } from './routes/api/public/bench.telemetry'
import { Route as ApiPublicBenchPairRouteImport } from './routes/api/public/bench.pair'
import { Route as ApiPublicBenchCommandsRouteImport } from './routes/api/public/bench.commands'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellUsuariosRoute = ShellUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRelatoriosRoute = ShellRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLaboratoriosRoute = ShellLaboratoriosRouteImport.update({
  id: '/laboratorios',
  path: '/laboratorios',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfiguracoesRoute = ShellConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAlertasIndexRoute = ShellAlertasIndexRouteImport.update({
  id: '/alertas/',
  path: '/alertas/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBancadasNovaRoute = ShellBancadasNovaRouteImport.update({
  id: '/bancadas/nova',
  path: '/bancadas/nova',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAlertasDestinosRoute = ShellAlertasDestinosRouteImport.update({
  id: '/alertas/destinos',
  path: '/alertas/destinos',
  getParentRoute: () => ShellRoute,
} as any)
const ApiPublicHooksCheckAlertsRoute =
  ApiPublicHooksCheckAlertsRouteImport.update({
    id: '/api/public/hooks/check-alerts',
    path: '/api/public/hooks/check-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBenchTelemetryRoute = ApiPublicBenchTelemetryRouteImport.update({
  id: '/api/public/bench/telemetry',
  path: '/api/public/bench/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBenchPairRoute = ApiPublicBenchPairRouteImport.update({
  id: '/api/public/bench/pair',
  path: '/api/public/bench/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBenchCommandsRoute = ApiPublicBenchCommandsRouteImport.update({
  id: '/api/public/bench/commands',
  path: '/api/public/bench/commands',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tv': typeof TvRoute
  '/configuracoes': typeof ShellConfiguracoesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/laboratorios': typeof ShellLaboratoriosRoute
  '/relatorios': typeof ShellRelatoriosRoute
  '/usuarios': typeof ShellUsuariosRoute
  '/alertas/destinos': typeof ShellAlertasDestinosRoute
  '/bancadas/nova': typeof ShellBancadasNovaRoute
  '/alertas/': typeof ShellAlertasIndexRoute
  '/api/public/bench/commands': typeof ApiPublicBenchCommandsRoute
  '/api/public/bench/pair': typeof ApiPublicBenchPairRoute
  '/api/public/bench/telemetry': typeof ApiPublicBenchTelemetryRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tv': typeof TvRoute
  '/configuracoes': typeof ShellConfiguracoesRoute
  '/dashboard': typeof ShellDashboardRoute
  '/laboratorios': typeof ShellLaboratoriosRoute
  '/relatorios': typeof ShellRelatoriosRoute
  '/usuarios': typeof ShellUsuariosRoute
  '/alertas/destinos': typeof ShellAlertasDestinosRoute
  '/bancadas/nova': typeof ShellBancadasNovaRoute
  '/alertas': typeof ShellAlertasIndexRoute
  '/api/public/bench/commands': typeof ApiPublicBenchCommandsRoute
  '/api/public/bench/pair': typeof ApiPublicBenchPairRoute
  '/api/public/bench/telemetry': typeof ApiPublicBenchTelemetryRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/tv': typeof TvRoute
  '/_shell/configuracoes': typeof ShellConfiguracoesRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/laboratorios': typeof ShellLaboratoriosRoute
  '/_shell/relatorios': typeof ShellRelatoriosRoute
  '/_shell/usuarios': typeof ShellUsuariosRoute
  '/_shell/alertas/destinos': typeof ShellAlertasDestinosRoute
  '/_shell/bancadas/nova': typeof ShellBancadasNovaRoute
  '/_shell/alertas/': typeof ShellAlertasIndexRoute
  '/api/public/bench/commands': typeof ApiPublicBenchCommandsRoute
  '/api/public/bench/pair': typeof ApiPublicBenchPairRoute
  '/api/public/bench/telemetry': typeof ApiPublicBenchTelemetryRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tv'
    | '/configuracoes'
    | '/dashboard'
    | '/laboratorios'
    | '/relatorios'
    | '/usuarios'
    | '/alertas/destinos'
    | '/bancadas/nova'
    | '/alertas/'
    | '/api/public/bench/commands'
    | '/api/public/bench/pair'
    | '/api/public/bench/telemetry'
    | '/api/public/hooks/check-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tv'
    | '/configuracoes'
    | '/dashboard'
    | '/laboratorios'
    | '/relatorios'
    | '/usuarios'
    | '/alertas/destinos'
    | '/bancadas/nova'
    | '/alertas'
    | '/api/public/bench/commands'
    | '/api/public/bench/pair'
    | '/api/public/bench/telemetry'
    | '/api/public/hooks/check-alerts'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/tv'
    | '/_shell/configuracoes'
    | '/_shell/dashboard'
    | '/_shell/laboratorios'
    | '/_shell/relatorios'
    | '/_shell/usuarios'
    | '/_shell/alertas/destinos'
    | '/_shell/bancadas/nova'
    | '/_shell/alertas/'
    | '/api/public/bench/commands'
    | '/api/public/bench/pair'
    | '/api/public/bench/telemetry'
    | '/api/public/hooks/check-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  TvRoute: typeof TvRoute
  ApiPublicBenchCommandsRoute: typeof ApiPublicBenchCommandsRoute
  ApiPublicBenchPairRoute: typeof ApiPublicBenchPairRoute
  ApiPublicBenchTelemetryRoute: typeof ApiPublicBenchTelemetryRoute
  ApiPublicHooksCheckAlertsRoute: typeof ApiPublicHooksCheckAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/usuarios': {
      id: '/_shell/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof ShellUsuariosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/relatorios': {
      id: '/_shell/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof ShellRelatoriosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/laboratorios': {
      id: '/_shell/laboratorios'
      path: '/laboratorios'
      fullPath: '/laboratorios'
      preLoaderRoute: typeof ShellLaboratoriosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/configuracoes': {
      id: '/_shell/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ShellConfiguracoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/alertas/': {
      id: '/_shell/alertas/'
      path: '/alertas'
      fullPath: '/alertas/'
      preLoaderRoute: typeof ShellAlertasIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bancadas/nova': {
      id: '/_shell/bancadas/nova'
      path: '/bancadas/nova'
      fullPath: '/bancadas/nova'
      preLoaderRoute: typeof ShellBancadasNovaRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/alertas/destinos': {
      id: '/_shell/alertas/destinos'
      path: '/alertas/destinos'
      fullPath: '/alertas/destinos'
      preLoaderRoute: typeof ShellAlertasDestinosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/public/hooks/check-alerts': {
      id: '/api/public/hooks/check-alerts'
      path: '/api/public/hooks/check-alerts'
      fullPath: '/api/public/hooks/check-alerts'
      preLoaderRoute: typeof ApiPublicHooksCheckAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bench/telemetry': {
      id: '/api/public/bench/telemetry'
      path: '/api/public/bench/telemetry'
      fullPath: '/api/public/bench/telemetry'
      preLoaderRoute: typeof ApiPublicBenchTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bench/pair': {
      id: '/api/public/bench/pair'
      path: '/api/public/bench/pair'
      fullPath: '/api/public/bench/pair'
      preLoaderRoute: typeof ApiPublicBenchPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bench/commands': {
      id: '/api/public/bench/commands'
      path: '/api/public/bench/commands'
      fullPath: '/api/public/bench/commands'
      preLoaderRoute: typeof ApiPublicBenchCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellConfiguracoesRoute: typeof ShellConfiguracoesRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellLaboratoriosRoute: typeof ShellLaboratoriosRoute
  ShellRelatoriosRoute: typeof ShellRelatoriosRoute
  ShellUsuariosRoute: typeof ShellUsuariosRoute
  ShellAlertasDestinosRoute: typeof ShellAlertasDestinosRoute
  ShellBancadasNovaRoute: typeof ShellBancadasNovaRoute
  ShellAlertasIndexRoute: typeof ShellAlertasIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellConfiguracoesRoute: ShellConfiguracoesRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellLaboratoriosRoute: ShellLaboratoriosRoute,
  ShellRelatoriosRoute: ShellRelatoriosRoute,
  ShellUsuariosRoute: ShellUsuariosRoute,
  ShellAlertasDestinosRoute: ShellAlertasDestinosRoute,
  ShellBancadasNovaRoute: ShellBancadasNovaRoute,
  ShellAlertasIndexRoute: ShellAlertasIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  TvRoute: TvRoute,
  ApiPublicBenchCommandsRoute: ApiPublicBenchCommandsRoute,
  ApiPublicBenchPairRoute: ApiPublicBenchPairRoute,
  ApiPublicBenchTelemetryRoute: ApiPublicBenchTelemetryRoute,
  ApiPublicHooksCheckAlertsRoute: ApiPublicHooksCheckAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
